services:
  react-app:
    build: client/
    restart: always
    volumes:
      - ./client/:/app
      - /app/node_modules
    ports:
      - "5173:5173"

  flask-app:
    build: .  # Replace with path to your Flask app directory
    restart: always
    volumes:
      - ./app/:/src/
    ports:
      - "5000:5000"  # Flask app port (can be customized)
        #    environment:
     #- FLASK_ENV=development  # Optional: Set Flask environment

  nginx:
    image: nginx:latest
    restart: always
    links:
      - flask-app:flask-app
      - react-app:react-app
    ports:
      - "80:80"  # Host port to access the application
    depends_on:
      - flask-app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Mount your Nginx config


